### ISSUE TITLE
Bundle autoprefixer by default

### ISSUE THREAD

**Issue by paulmillr** [brunch/postcss-brunch#12]
Postcss-brunch requires users to specify unnecessary config options. This is not "Brunches way".

I suggest we bundle autoprefixer by default and let users specify if they want to disable it.

autoprefixer-brunch, which is deprecated is more than 50% of all postcss-brunch installations.

**Comment by rstacruz** [comment]
:-1: on this. Most PostCSS "meta-plugins" already include autoprefixer; in fact, I typically use http://cssnext.io/ instead of autoprefixer.
