### ISSUE TITLE
Bump version to 2.0

### ISSUE THREAD

**Issue by paulmillr** [brunch/postcss-brunch#15]
This would conform to Brunch plugin version guidelines. Could you do a quick version bump? @iamvdo

**Comment by iamvdo** [comment]
I can't find these guidelines, where are they ?

**Comment by paulmillr** [comment]
I haven't written them down probably. But almost all plugins conform to it.

If it's for Brunch 2.x, then the plugin should be 2.x.
Brunch 3.x and 3.x. etc.

**Comment by iamvdo** [comment]
Never heard of that kind of versioning. What about semver and own plugin lifecycle ?

**Comment by paulmillr** [comment]
What about it? The versioning for Brunch conforms to semver. 2.x plugins work with 2.x brunch and similar.
