### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by rstacruz** [brunch/postcss-brunch#25]
What happened in v0 to v1 to v2?

**Comment by rstacruz** [comment]
I've updated from 0.5.0 to 2.0.3 and it stopped working. It's probably a change in configuration or something...

**Comment by paulmillr** [comment]
We have refactored the implementation and improved warning output. I don't think it's a change in configuration - may be some new issue in postcss-brunch. Have you got to the real issue underneath? Is there any way I could reproduce the state?

**Comment by kuon** [comment]
You might have hit https://github.com/brunch/postcss-brunch/issues/18 2.0.5 still not working for me with sass.
