### ISSUE TITLE
csswring example is likely wrong

### ISSUE THREAD

**Issue by rstacruz** [brunch/postcss-brunch#26]
From the readme:

``` js
  postcss: {
    processors: [
      require('autoprefixer')(['last 8 versions']),
      require('csswring') // <--
    ]
  }
}
```

I think that needs to be:

``` js
require('csswring')()
```

The [documentation for csswring](https://www.npmjs.com/package/csswring#usage) says it's used that way, and most PostCSS plugins are invoked in the same manner.

**Comment by paulmillr** [comment]
Fixed!
