### ISSUE TITLE
Release build with working css modules support

### ISSUE THREAD

**Issue by razor-x** [brunch/postcss-brunch#27]
Please release either 2.1.0 or 2.0.4 based on 29d990c7b6921295bd3e48536371abeab9604c64 but not HEAD. The PR adding css modules was non-breaking and only adds an opt-in feature (that I would like to start using).

If you are going to release a build based on 1ab2a925b81148b59feb7a5bca0babec0e74c827, then it would need to be a major version bump and would also break module support. Please refer the discussion here for details: https://github.com/brunch/postcss-brunch/pull/24

**Comment by natecox** [comment]
Would love to see more commentary on this; I'm trying to build a workflow for a new project, and it would be very helpful to see which direction this package is going to take (i.e., compiler vs optimizer). I would strongly support the compiler direction, as this package has made it possible for me to use css modules in React via Elixir/Phoenix and Brunch.

**Comment by paulmillr** [comment]
Folks — we are discussing the release with @shvaikalesh. Need to adjust one small thing before the release and maybe revert optimize. Will post ASAP.

**Comment by natecox** [comment]
Awesome, thanks for the reply

**Comment by shvaikalesh** [comment]
Hey guys, thanks for all the contributions and discussions: we highly appreciate the support. PostCSS is, _semantically_, the compiler. We should make a few adjustments to Brunch itself to support `postcss-brunch` working after the preprocessors. We also want to support the usage of `postcss` alone, cause it is awesome, and without the need of specifying `css-brunch`. Will keep you in the loop.

**Comment by paulmillr** [comment]
pushed

**Comment by lydell** [comment]
> PostCSS is, _semantically_, the compiler. We should make a few adjustments to Brunch itself to support `postcss-brunch` working after the preprocessors.

@shvaikalesh That’s great to hear! Is this tracked somewhere? I’m very eager to get Sass+PostCSS work without hacks! :)

**Comment by lydell** [comment]
I guess that is now tracked in #31.
