### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by dmitrykiselyov** [brunch/postcss-brunch#3]
I tried with the [base skeleton](https://github.com/brunch/dead-simple) and nothing happens. CSS is the same :confused:

**Comment by LaurentTreguier** [comment]
I already tried and noticed this problem (#1), and I'm waiting for my fix (#2) to be merged.

**Comment by dmitrykiselyov** [comment]
@LaurentTreguier Yes, your fix works :+1: But, before updating the postcss-brunch node_module postcss to 4.1.5, CSS MQPacker was working, but Autoprefixer is not. After updating postcss, vice versa, Autoprefixer is working, CSS MQPacker is not  :smile:

**Comment by dmitrykiselyov** [comment]
Works fine :clap:

``` coffee
  plugins:
    postcss:
      config: (postcss) ->
        postcss().
        use(require('autoprefixer')(['last 3 versions']).postcss).
        use(require('lost').postcss)
```

**Comment by LaurentTreguier** [comment]
I don't use MQPacker so I didn't notice that issue... Perhaps it's MQPacker itself ? Its DevDependencies show PostCSS 4.0.0 is used. Maybe try with that version instead of the latest ?

**Comment by dmitrykiselyov** [comment]
I discovered new issue :scream: 
When @import a file in Stylus or Sass, it remains unchanged. In Less is ok.

An example with Autoprefixer:
_In Stylus is need to use the CSS syntax to make it work!_

`s1.styl`

``` stylus
.s1 {
  display: flex;
}
@import 's2'
```

`s2.styl`

``` stylus
.s2 {
  display: flex;
}
```

Compiled CSS `s1.css`

``` css
.s1 {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
.s2 {
  display: flex;
}
```

**Comment by LaurentTreguier** [comment]
Well that's another topic... PostCSS shouldn't be the one compiling SASS or stylus, [sass-brunch](https://github.com/brunch/sass-brunch) and [stylus-brunch](https://github.com/brunch/stylus-brunch) should do that.

**Comment by dmitrykiselyov** [comment]
@LaurentTreguier
stylus-brunch + postcss-brunch + autoprefixer **don't add vendor prefixes** 
stylus-brunch + autoprefixer-brunch **add vendor prefixes**
It's mean that problem in the postcss-brunch, right?

postcss-brunch should handle compiled css after stylus-brunch / sass-brunch
@iamvdo Do you know how to solve it?

**Comment by LaurentTreguier** [comment]
Well that sounds even weirder... Maybe brunch doesn't do anything because a single plugin isn't working (not loading correctly or something similar).

**Comment by dmitrykiselyov** [comment]
I found a solution :+1: 
PR will be tomorrow :wink:

**Comment by iamvdo** [comment]
Hey !
Last commit was more than 1 year ago, so yes there are many issues. This module have to be completely rewritten.

Help is welcome ;)
I will work on it.

**Comment by dmitrykiselyov** [comment]
@iamvdo :+1: 

Ok, my super solution is:

**remove**
`PostCSSCompiler.prototype.pattern`
`PostCSSCompiler.prototype.compile` In the Brunch [API](https://github.com/brunch/brunch/blob/stable/docs/plugins.md#api) specified that:
`compile(data` Data is contents of **source** file which will be compiled (.css, .styl, .scss, .less)
`optimize(data` Data is contents of **destination** file which will be optimized/minified (.css)
As I understand it, we should use `optimize` because the `data` contained all code style (vanilla CSS), which was created from other .css, .styl, . .sass, .less.

**add**
`PostCSSCompiler.prototype.defaultEnv = '*';` I don't know what it [does](https://github.com/brunch/brunch/blob/cc84b3c9e9c79def0bbf9418f86630ed23ad2c23/src/watch.coffee#L419) :smile:, but without this property does not work. I tried to implement a code from different brunch plugins, but working variant came from the [autoprefixer-brunch](https://github.com/lydell/autoprefixer-brunch/blob/master/lib/index.js#L19)

**postcss v4.1.5**

``` js
var postcss = require('postcss');
var PostCSSCompiler;

module.exports = PostCSSCompiler = (function() {

    PostCSSCompiler.prototype.brunchPlugin = true;
    PostCSSCompiler.prototype.type = 'stylesheet';
    PostCSSCompiler.prototype.extension = 'css';
    PostCSSCompiler.prototype.defaultEnv = '*';
    PostCSSCompiler.prototype.defaults = {
        config: function (postcss) {
            return postcss();
        }
    }

    function PostCSSCompiler(config) {

        this.config = config;
        var _ref;
        if ((_ref = this.config.plugins) != null) {
            if (_ref.postcss) {
                for(var key in _ref.postcss){
                    if(_ref.postcss.hasOwnProperty(key)){
                        this.defaults[key] = _ref.postcss[key];
                    }
                }
            };
        };
        this.postcssConfig = this.defaults;

    };

    PostCSSCompiler.prototype.optimize = function(params, callback) {

        var _ref;
        if (typeof (_ref = this.postcssConfig).config === "function") {
            var result = _ref.config(postcss).process(params.data).css;
            return callback(null, result);
        }

    };

    return PostCSSCompiler;

})();
```

So it's work fine with this plugins:

``` coffee
  plugins:
    postcss:
      config: (postcss) ->
        postcss().        
        use(require('pixrem').postcss).
        use(require('postcss-default-unit').postcss).        
        use(require('postcss-color-alpha').postcss).    
        use(require('autoprefixer')(['last 1 versions']).postcss).
        use(require('lost').postcss).
        use(require('css-mqpacker').postcss)
```

but with this:

``` coffee
  plugins:
    postcss:
      config: (postcss) ->
        postcss().        
        use(require('postcss-size').postcss).        
        use(require('postcss-at2x').postcss).
        use(require('postcss-font-variant').postcss).        
        use(require('postcss-custom-selectors').postcss)
```

throws an error:

```
\dead-simple-master
\node_modules\postcss-brunch\node_modules\postcss\lib\lazy-result.js:154
            if (plugin.postcssVersion) {
                      ^
TypeError: Cannot read property 'postcssVersion' of undefined
```

@iamvdo So what to do? Create PR with my super solution or you will work on it?

**Comment by LaurentTreguier** [comment]
@dmitrykiselyov Shouldn't `compile` be used instead of `optimize` ? The code before being processed by PostCSS is not actually valid CSS, so it's more likely a compiler than an optimizer. An optimizer sould be optional, while PostCSS is mandatory or else your CSS code won't work...

**Comment by iamvdo** [comment]
As I understand it:
- `compile` is for each source files, independently (CSS or else)
- `optimize` is for final compiled file

Both are important, and sometimes required (when you use CSS custom properties, CSS Media-queries packer, from multiple files for example).

I've worked on a new version, I will publish it soon. It's very simple for now, but it will be easier to open related issues :)

**Comment by dmitrykiselyov** [comment]
@LaurentTreguier `compile` give us the code, for example from main.styl,  before compiling it, as a result, throws an error, because PostCSS requires vanilla CSS. 
@iamvdo :+1: We will wait :smiley:  Thank you!

**Comment by LaurentTreguier** [comment]
@dmitrykiselyov You're right ; and from the [plugin API page](https://github.com/brunch/brunch/blob/stable/docs/plugins.md#api) it even seems `compile` and `optimize` are the exact same, except that one is called before the other.

**Comment by iamvdo** [comment]
Released 0.3.0. I've made changes in API, see readme.
Will close this issue, feel free to open new specific ones. ;)

**Comment by dmitrykiselyov** [comment]
@iamvdo Nope, without `PostCSSCompiler.prototype.defaultEnv = '*';` not working!

Also, we don't need `PostCSSCompiler.prototype.pattern = /\.(?:css|scss|sass|less|styl)$/;` because PostCSS doesn't understand preprocessor dialect :laughing: 

Also, we don't need `PostCSSCompiler.prototype.compile` because he does the same thing as  `PostCSSCompiler.prototype.optimize` 

Also, when using both `compile` and `optimize`, it may cause an error, because it will handle CSS twice. For example when using postcss-font-variant `font-feature-settings: "c2sc", "c2sc";` insted `font-feature-settings: "c2sc";` But it can be a problem in the plugin.

If we need to use `compile` **we need to figure out how to receive to it compiled code from preprocessors**. And use `optimize` only if it is necessary for a plugin!

I have successfully tested this plugins:

`brunch-config.coffee`

``` coffee
  plugins:
    postcss:
      processors: [ 
        require('pixrem'),
        require('lost'),
        require('postcss-color-alpha'),
        require('postcss-default-unit'),        
        require('postcss-at2x')(),
        require('postcss-font-variant')(),
        require('postcss-custom-selectors')(),
        require('autoprefixer')(),        
        require('postcss-size'),
        require('css-mqpacker')
      ]
```

`index.js`

``` js
var postcss = require('postcss');
var PostCSSCompiler;

module.exports = PostCSSCompiler = (function() {

  PostCSSCompiler.prototype.brunchPlugin = true;
  PostCSSCompiler.prototype.type = 'stylesheet';
  PostCSSCompiler.prototype.extension = 'css';
  PostCSSCompiler.prototype.defaultEnv = '*';

  function PostCSSCompiler(config) {
    this.processors = [];
    if (config.plugins && config.plugins.postcss) {
      if (config.plugins.postcss.processors) {
        this.processors = config.plugins.postcss.processors;
      }
    }
  };

  PostCSSCompiler.prototype.optimize = function(params, callback) {
    var result = postcss(this.processors).process(params.data).css;
    return callback(null, result);
  };

  return PostCSSCompiler;

})();
```

**Comment by iamvdo** [comment]
I've never heard about the `defaultEnv` property, then I read this https://github.com/brunch/brunch/issues/748
So, I've made changes that you've mentioned, released in postcss-brunch@0.3.1

**Comment by iamvdo** [comment]
But I still think that both `compile` and `optimize` are required (for good sourcemaps generation for example). If you use preprocessors, then postcss-brunch `optimize` does the job, but if not, you need `compile` to get correct `from` option from each source file.

**Comment by dmitrykiselyov** [comment]
Thank you :+1:
Maybe add ability to choose between `compile` and `optimize`.
For example by default would be `compile`, but if I use preprocessor, I can set in options `preprocessor: true.` and it will be using `optimize`.

``` coffee
  plugins:
    postcss:
      options:
        preprocessor: true      
      processors: [
        require('pixrem')
      ]
```

``` js
var postcss = require('postcss');
var PostCSSCompiler;

module.exports = PostCSSCompiler = (function() {

  PostCSSCompiler.prototype.brunchPlugin = true;
  PostCSSCompiler.prototype.type = 'stylesheet';
  PostCSSCompiler.prototype.extension = 'css';
  PostCSSCompiler.prototype.defaultEnv = '*';

  function PostCSSCompiler(config) {
    this.options = false;
    this.processors = [];   

    if (config.plugins && config.plugins.postcss) {
      if (config.plugins.postcss.options !== undefined) {
        this.options = config.plugins.postcss.options;
      }
      if (config.plugins.postcss.processors !== undefined) {
        this.processors = config.plugins.postcss.processors;
      }      
    }
  };

  PostCSSCompiler.prototype.compile = function(params, callback) {

    // If we using vanilla CSS
    if (this.options.preprocessor === undefined || !this.options.preprocessor) {
      var result = postcss(this.processors).process(params.data).css;
      return callback(null, result);
    }     
    return callback(null, params.data);  

  };

  PostCSSCompiler.prototype.optimize = function(params, callback) {

    // If we using CSS preprocessor(s)
    if (this.options.preprocessor) {
      var result = postcss(this.processors).process(params.data).css;
      return callback(null, result);
    }     
    return callback(null, params.data);

  };

  return PostCSSCompiler;

})();
```

**Comment by es128** [comment]
Just wanted to mention in this thread - sorry for the (prior) lack of documentation for `defaultEnv`, and thanks to @dmitrykiselyov for [bringing it to my attention](https://github.com/brunch/brunch/issues/965).
