### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by rstacruz** [brunch/postcss-brunch#31]
I cant get 2.0.5 working on Brunch 2.9.1. Previously, Brunch 2.8.2 + postcss-brunch 0.5.0 was running fine.

PostCSS doesn't happen. I tried adding console.log's to `node_modules/postcss-brunch/index.js` and the `compile(file)` method doesn't get called.
- brunch-config.js and package.json: https://gist.github.com/rstacruz/5d185dc9d346e98195142ddc12b28386
- Node 6.3.0
- Brunch 2.9.1

**Comment by rstacruz** [comment]
Oh, I'm also using sass-brunch. My expectation is that sass compiles into CSS which gets potscss'd.

**Comment by lydell** [comment]
In my opinion, using a Sass + autoprefixer pipeline is very common and should be easy to set up.

This is what I use in my projects for now as a workaround:

``` json
"devDependencies": {
  "autoprefixer": "^6.4.0",
  "brunch": "brunch/brunch#ee73ef0f92add24b46c4478fa3f0b5bc206bbe7d",
  "postcss-brunch": "brunch/postcss-brunch#07961d39cecfbc9aa02b48259bb551e56defd4e8",
  "sass-brunch": "^2.7.0"
}
```

**Comment by kuon** [comment]
I don't know if this is https://github.com/brunch/postcss-brunch/issues/18 back, but seems so.

**Comment by kuon** [comment]
Even version 0.5.0 doesn't work with brunch 2.9.1 it seems.

**Comment by lydell** [comment]
@kuon See me previous comment. That works.

**Comment by kgcreative** [comment]
@lydell -- Having the exact same issue as @rstacruz .

Your workaround to postcss-brunch worked perfectly.
~~I only needed to enable the postcss-brunch updates, not the brunch ones (2.9.1)~~
Correction, I actually need both of those versions. Updated gist below.

current configuration:
https://gist.github.com/kgcreative/ce396ce58e096f0c52845e3038d2b5b1

**Comment by nshafer** [comment]
The workaround works for me as well, using Stylus and then piping it to PostCSS. Will keep an eye out for official fixes, but for now pinning those two specific checkouts works and got me back in business. Thanks @lydell.

**Comment by rstacruz** [comment]
Our workaround is to pin those versions (postcss-brunch 0.5.x and Brunch 2.8.x). Any other combination with recent versions don't work.

**Comment by kgcreative** [comment]
Any updates on a resolution to this? I'd like to be able to upgrade my production code to something that won't break on an unintended npm update

**Comment by kuon** [comment]
I did open https://github.com/brunch/sass-brunch/issues/124 to add postcss configuration directly into sass-brunch.

**Comment by nshafer** [comment]
I use Stylus in my current project, so that wouldn't help me, nor anyone else with non-sass workflows.

**Comment by lydell** [comment]
To me, it seems like Brunch needs to support several compilers in a chain. Examples:
- Sass (.scss or .sass) → PostCSS (.css)
- Stylus (.styl) → PostCSS (.css)
- Less (.less) → PostCSS (.css)
- CoffeeScript (.coffee) → Babel (.js) (*)

(*) CoffeeScript 1.11.0+ supports ES2015 `import` and `export` syntax. Since no browsers support import/export yet, the CoffeeScript output needs to go through Babel.

**Comment by rstacruz** [comment]
Can confirm the observations above. We're sticking with brunch 2.8 and
postcss-brunch 0.5 for this reason.

**Comment by kuon** [comment]
@nshafer yeah, I don't know what is the best approach. sass-brunch already depends on postcss, that's why I did think about integrating autoprefixer in it.

**Comment by reubano** [comment]
What's the status on this? Is it working with `sass`?
