### ISSUE TITLE
ignore vendor css files

### ISSUE THREAD

**Issue by jmls** [brunch/postcss-brunch#32]
I only want to run autoPrefix on my css files in src .. 

I have

```
            postcss: {
                processors: [
                  require('autoprefixer')(['last 8 versions'])
                ]
            },
```

configured in the `plugins` section

however, when brunch building, I get the error

`01 Nov 16:26:25 - error: Compiling of bower_components/material-design-lite/material.min.css failed. "/stdin" is not in the SourceMap. `

I would expect a vendor library to be already "autoprefixed". so want to exclude anything outside the src folder in the configuration

I have tried `files`, `ignore` and a couple of others to no effect 

Is there a magic incantation I can use ? Or have I simply missed the option in config ?

thanks

**Comment by jmls** [comment]
I have forked and added an `ignore` section for the plugin - it worked well for me, but I don't know if this would work for anyone else. At the moment, it is a change of default behaviour (I want to ignore bower_components and vendor by default) 

Let me know if you want me to create a PR

**Comment by rstacruz** [comment]
Did you try [conventions.ignored](http://brunch.io/docs/config#-conventions-) yet?

```js
conventions: {
  ignored: [ /bower_components/ ]
}
```

**Comment by rstacruz** [comment]
...hmm, actually, I see what you mean—a file makes sense to be compiled and included in the bundle, but not processed by postcss. This is much like how Browserify/Webpack/Brunch would leave `node_modules/` alone.

I think it makes sense and PR would be appreciated. FYI: `babel-brunch` has this setting too:

```js
/* babel-brunch */
plugins: {
  babel: {
    ignore: [ /^(bower_components|vendor)/ ] } }
```

It only makes sense for postcss-brunch to have it too. @paulmillr?

**Comment by paulmillr** [comment]
@rstacruz yes
