### ISSUE TITLE
Support stylelint with 0 config

### ISSUE THREAD

**Issue by shvaikalesh** [brunch/postcss-brunch#34]

**Comment by rstacruz** [comment]
👎 there are many ways to integrate stylelint, and many people prefer linting to be an additional step to compiling. this would break many workflows.

also, 0-configuration stylelint wouldn't be sensible considering there are many available stylelint configurations out there.

**Comment by shvaikalesh** [comment]
Sure, we won't break anything and will not provide some default config. However, if user has one, Brunch would use it.
