### ISSUE TITLE
Support SugarSS with 0 config

### ISSUE THREAD

**Issue by shvaikalesh** [brunch/postcss-brunch#35]

**Comment by paulmillr** [comment]
what do you mean?

**Comment by shvaikalesh** [comment]
https://github.com/postcss/sugarss

We add it as a dependency to `postcss-brunch` and process `.sss` files without additional configuration.

**Comment by paulmillr** [comment]
Zero-config is good, but this is a plugin. Even if it's widely used, it may not be as popular in 1-2 years, and then we'll need to extract the functionality, while breaking the compatibility.

**Comment by shvaikalesh** [comment]
Otherwise, to support `.sss` and other parsers, we would need to add a config option. Same

> Even if it's widely used, it may not be as popular in 1-2 years, and then we'll need to extract the functionality, while breaking the compatibility.

holds true for option, but requires additional setup by users.

**Comment by rstacruz** [comment]
:-1: postcss-brunch isn't opinionated. maintaining another dependency would be a burden. this feels like it'd belong better in something like `sugarss-brunch`.

**Comment by shvaikalesh** [comment]
Brunch itself is opinionated. However, it is not quite about that: we should support PostCSS parsers. If the user has sugarss parser in package.json, `postcss-brunch` should use it.

**Comment by paulmillr** [comment]
Agree on `sugarss-brunch`.

**Comment by shvaikalesh** [comment]
If we do `sugarss-brunch` we end up maintaining several copy-pasted Brunch plugins for each parser PostCSS will ever have. It is way better to analyze `package.json` for PostCSS parsers instead of separate plugins.
