### ISSUE TITLE
Example of use with SASS Brunch?

### ISSUE THREAD

**Issue by silbinarywolf** [brunch/postcss-brunch#48]
From what I can tell, this doesn't work with SASS brunch configuration.
ie. This module: https://github.com/brunch/sass-brunch

**Comment by shvaikalesh** [comment]
It is a known issue. https://github.com/brunch/brunch/pull/1664 should fix this.

**Comment by DanielBlanco** [comment]
This fork worked for me https://github.com/helols/spostcss-brunch
