### ISSUE TITLE
Package version has not been updated to include PostCSS 6 fixes

### ISSUE THREAD

**Issue by LkeMitchll** [brunch/postcss-brunch#49]
Can we please get a new release to the package version so that we can install via npm easily? The current version does not contain a lot of helpful pull requests and commits.

The fix was merged in #47 and is very helpful for those using packages such as postcss-nesting and others.

**Comment by shvaikalesh** [comment]
Fixed by b9e2a385ce97488219a17c67077a10fbd9e59105
