### ISSUE TITLE
PostCSS Runner Guidelines

### ISSUE THREAD

**Issue by ai** [brunch/postcss-brunch#5]
All PostCSS runners muust pass [Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md).
- [ ] set `from` and `to` options.
- [ ] use async API.
- [ ] special output for `CssSyntaxError`.
- [ ] show warnings.
- [ ] `postcss-runner` keyword in `package.json`.

**Comment by ai** [comment]
You are the only one runner, who doesn’t pass Guidelines ;).

**Comment by ai** [comment]
@iamvdo any updates? If you have no time, say it, I will make a PR. Please, don’t ignore users.

**Comment by iamvdo** [comment]
I never ignore users. I simply don't have enough time. ;)
As I already mentioned before, I no longer use this module. I can still work on it, but don't expect fast updates. If you make PRs, I'll merge them.

**Comment by ai** [comment]
I send a PR https://github.com/iamvdo/postcss-brunch/pull/6

**Comment by iamvdo** [comment]
Fixed in @0.4.0
