### ISSUE TITLE
Cannot read property 'progeny' of undefined

### ISSUE THREAD

**Issue by lukakerr** [brunch/postcss-brunch#50]
I'm getting this warning when running `brunch b`: `warn: Loading of postcss-brunch failed due to Cannot read property 'progeny' of undefined`.  It's causing the CSS files to not get compiled

We are not using the progeny option in our config file:

```
plugins:
    postcss:
      processors: [require('autoprefixer')(["iOS 7", "iOS 8", "> 1%", "Firefox > 20"])]
```

This is happening with `"postcss-brunch": "2.1.0",`, but is not happening with v2.0.5

**Comment by hugosenari** [comment]
[Check if cfg is null](https://github.com/brunch/postcss-brunch/blob/master/index.js#L54)

**Comment by ubill** [comment]
Thanks @hugosenari , I solved this by putting this inside my brunch-config.js

```
  plugins: {
    postcss: {
    }
  }
```

then the error went away.
